### ISSUE TITLE
Add quality badges to the repository README

### ISSUE THREAD

**Issue by pkosiec** [capactio/capact#321]
## Description

- Generate quality badges:
   - [Github Actions](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge)
   - https://goreportcard.com/ 
   - https://bestpractices.coreinfrastructure.org/en
   - Consider Snyk and CodeClimate badges
- Check our score and fix detected issues

Timeboxed task, we do as much as we can in a given time.

## Reason

Show that we follow best practices during Capact development and that we do care about the quality of the project.

**Comment by Trojan295** [comment]
There are some problems with the Snyk badges https://github.com/snyk/snyk/issues/347. I wasn't able to get a score for the capact repo and for the website repo the badge appears randomly and takes long to load.

CodeClimate checks are similar to the Go Report Cards ones. Also, I wasn't able to enable them, as I'm not the repository owner.

**Comment by mszostok** [comment]
FYI: @Trojan295. Snyk works only with Ruby, Java and Node.js; that was the reason why you couldn't generate a badge for `capact` repo. Nevertheless, they support monorepo, so we can have badge for our `hub-js`, here is the link: https://snyk.io/test/github/capactio/capact/badge.svg?targetFile=hub-js/package.json

Question whether we want to have it on main repo. It can be misleading for others as we cannot change the default name `vulnarabilites` to sth like `hub-js vulnarabilites`. Additionally, it is really slow as described in issue mentioned by @Trojan295

**Comment by pkosiec** [comment]
I vote for skipping the Snyk badge from our repo 👍

**Comment by mszostok** [comment]
Configure our linter on CI to report if we miss comment for public vars/funcs
