### ISSUE TITLE
Prepare migration from 0.3.0 to 0.4.0

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#324]
## Description

We need to have migration from 0.3.0 to 0.4.0 release. 

Breaking changes:
- To find breaking changes, use this filter: https://github.com/capactio/capact/pulls?q=is%3Apr+label%3Abreaking+

**AC:**

- Automatic migration or manual migration guide

## Reason

We have already clusters which run version 0.3.0. To make upgrade smoother, we need to test and describe migration to a new release.

**Comment by pkosiec** [comment]
As agreed, we won't support migration from 0.3.0.
