### ISSUE TITLE
Modify the OCH manifests

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#331]
## Description

 1. OCF Schema: Add `additionalInput` for Implementation to OCF JSON schema
 1. Cleanup Interface parameters for all manifests. Move all K8s specific params to `Implementation.additionalInput` with dedicated JSON schema
 1. Remove Impl-specific Interfaces and Implementations for RDS and Elasticsearch 
     1. Reduce the Implementations to single one with `additionalInput` with dedicated JSON schema
     1. You don’t need to install all apps to verify - just compare values.yaml
 1. Create one Type with shared k8s parameters - If possible
     1. If there are common parameters from `additionalInput` for different Implementations, extract them to dedicated Type
 1. Update tutorials if needed

**Comment by Trojan295** [comment]
Closed by https://github.com/capactio/hub-manifests/pull/3
