### ISSUE TITLE
Native support to validate the whole hub manifest via `capact validate`

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#346]
## Description

In CLI docs, we have:

```bash
# Validate multiple files inside test_manifests directory
capact validate pkg/cli/test_manifests/*.yaml

# Validate all OCH manifests
capact validate ./och-content/**/*.yaml
```

But this shell expansion depends on a given platform, e.g. on our CI it doesn't work: https://github.com/capactio/hub-manifests/runs/2819063889?check_suite_focus=true

## Reason

We should implement a native support for validating the whole Hub manifest directory. In that way, our documentation will be consistent across all platforms, and we will improve UX. Currently, it's error-prone.

**Comment by mkuziemko** [comment]
my initial thoughts/options for solving this issue from user-perspective:

example data:
```
/pkg/sdk/validation/manifest/testdata $ tree .
.
├── invalid-implementation.yaml
├── invalid-interface_json-schema.yaml
├── invalid-interface.yaml
├── invalid-manifest.yaml
├── invalid-type_json-schema.yaml
├── invalid-type.yaml
├── subdirectory_testdata
│   └── valid-interface.yaml
├── valid-implementation.yaml
└── valid-type.yaml
```

1. user can specify multiple arguments, each of them is a path to a file or directory
```
capact manifests validate ./pkg/sdk/validation/manifest/testdata/valid-type.yaml ./pkg/sdk/validation/manifest/testdata/valid-implementation.yaml
```
2. If one of the paths in the list, is a directory then there will be a validation for every file within the catalog
for instance: 
```
capact manifests validate ./pkg/sdk/validation/manifest/testdata/
```
every file from testdata will be validated but with no recursion (_without_ `subdirectory_testdata`)

3. There is additionally, the `-r` parameter for searching recursively,
```
capact manifests validate -r ./pkg/sdk/validation/manifest/testdata/
```
every file from testdata will be validated but with recursion (_with_ `subdirectory_testdata`)


Additionally:
- slash in the end is important, `./pkg/sdk/validation/manifest/testdata/` with work compare to `./pkg/sdk/validation/manifest/testdata` (error message)
- by default, there is searching only for `.yaml` files from the catalog (perhaps make it configurable?) 

Suggestions or comments are welcome :+1:

**Comment by mszostok** [comment]
I like your idea for solving that issue 👍 

>Additionally:
>- slash in the end is important, `./pkg/sdk/validation/manifest/testdata/` with work compare to `./pkg/sdk/validation/manifest/testdata` (error message)
>- by default, there is searching only for `.yaml` files from the catalog (perhaps make it configurable?) 


1. Could you explain why u want to return an error in case of missing `/` at the end of the directory? AFAIK I don't remember any tool to return an error in such situation. With the `os` lib we will know whether it's file or dir, and we can trigger a proper logic as you described in the proposal :)
2. It's good to narrow-down the search criteria 👍 . It can be configurable via flag as you said or just extend search criteria to include `.yaml` , `.yml` as those are the most popular extensions for YAMLs. Of course, they can store it even without extension or with `.txt` but I don't see a valid reason for that, so we can ignore them by default. If you go with CLI flag, make use slice, so the user can pass two exts at once e.g., `--ext/--extensions "yaml,yml"`, as there may be a situation where Hub uses both extensions. It shouldn't, but we know the reality ;)
