### ISSUE TITLE
Capact CLI doesn't support Keychain backend on macOS

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#405]
## Description

Cannot use `macOS/OSX Keychain` for storing login credentials details.

## Expected behavior

By default, the `macOS/OSX Keychain` backend is used for credentials store on macOS.

## Actual behavior

By default, the `file` backend is used and in "happy path" scenario, the user is prompted to enter a password for each executed command.

## Investigation

We use the https://github.com/99designs/keyring lib which uses cgo under the hood for `macOS/OSX Keychain`. For building Capact CLI  we disabled CGO and we use upx to reduce binary size. 

Links:
- keychain lib: https://github.com/99designs/keyring/blob/d9b6b92e219ff56ce753cf84d4956f823d431651/keychain.go#L1
- disabled CGO: https://github.com/capactio/capact/blob/main/.goreleaser.yml#L17

## Possible options

- Enable CGO and remove upx optimization. For example, `kubectl` has 50mb, and it's not optimized. 
- Switch to different library which doesn't use c binding. For example, https://github.com/zalando/go-keyring - check if upx will work with that

## Additional info

- In case of not having macOS we can use [GitHub Actions macOS runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) for testing or [EC2 Mac instance](https://aws.amazon.com/ec2/instance-types/mac/)

**Comment by mszostok** [comment]
Proposed approach:
1. Check if a simple CLI with https://github.com/zalando/go-keyring#example-usage is working properly with UPX.
2. Missing method `Keys()` on **zalando** lib.
  Solution: We should migrate it to `[config](https://github.com/capactio/capact/tree/main/internal/cli/config)` storage, as we still need to support `capact config get-contexts`. We don't need to bind it to env variable.
3. Missing drivers
  Solution: use the **zalando** only with darwin build. But still support `pass` and `file` backends. **Daft** (**really draft** :D) idea here: (https://github.com/capactio/capact/compare/main...mszostok:keyring-try?expand=1)

**Comment by mkuziemko** [comment]
Current status: 
(1) I build example usage on macOS and use `upx` on it - works fine. 
(2) Keys() - logic transferred to to `config` package as suggested (PR will be added soon)
(3) I used `zalando` and `upx` - works fine. Although, there are a couple of things to consider/improve: 
- `zalondo` uses a `security` binary and in case it is something wrong, return only an exit code that is not user-friendly.  Perhaps, we could make a contribution or wrap an error on our side. 
- in the case of using a keychain, it needed to be created first:
```
security create-keychain 
security default-keychain -s keychain_name
```
Then, if everything works correctly and execute our binary, we could check if there is a new `capact` key in the keychain:
```
security dump-keychain keychain_name | grep "capact"
```
