### ISSUE TITLE
Create/Use dedicated package for string slices

### ISSUE THREAD

**Issue by lukaszo** [capactio/capact#411]
## Description

Currently, in a different places of the code we have functions to, for example, check if slice [contains a string](https://github.com/capactio/capact/blob/main/internal/cli/capact/components.go#L560). 

The task is to find such duplicated pieces and move them to a one package. We may re-use https://github.com/kubernetes/utils/blob/master/strings/slices/slices.go or base our solution on it.

It's a good issue for a first-time contributor.

**Comment by krishnaindani** [comment]
hey, could I try to work on this issue?

**Comment by platten** [comment]
We welcome all contributions 😀 If you have any questions, please feel free to reach out to us on our [slack channel](https://capact.io/slack). Thanks!

**Comment by krishnaindani** [comment]
I only see one place where this is used, so created a PR here https://github.com/capactio/capact/pull/416
