### ISSUE TITLE
`capact act watch` cannot be stopped

### ISSUE THREAD

**Issue by lukaszo** [capactio/capact#472]
## Description

`capact act watch` cannot be stopped using ctrl-c

## Expected behavior

should stop

## Actual behavior

doesn't stop :)

## Steps to reproduce

* create any action
* run it
* watch it
* try to stop it

**Comment by pkosiec** [comment]
We use argo watch command directly and looks like they don't use `Context` from Cobra command:

```go
		Run: func(cmd *cobra.Command, args []string) {
			if len(args) != 1 {
				cmd.HelpFunc()(cmd, args)
				os.Exit(1)
			}
			ctx, apiClient := client.NewAPIClient() // <-- Here
			serviceClient := apiClient.NewWorkflowServiceClient()
			namespace := client.Namespace()
			watchWorkflow(ctx, serviceClient, namespace, args[0], getArgs)
		}, 
```

Going few levels deeper, we have:

```go
	gatekeeper, err := auth.NewGatekeeper(auth.Modes{auth.Server: true}, clients, restConfig, nil, auth.DefaultClientForAuthorization, "unused")
	if err != nil {
		return nil, nil, err
	}
	ctx, err := gatekeeper.Context(context.Background())
```

And what gatekeeper does is adding few values:

```go
func (s *gatekeeper) Context(ctx context.Context) (context.Context, error) {
	clients, claims, err := s.getClients(ctx)
	if err != nil {
		return nil, err
	}
	ctx = context.WithValue(ctx, WfKey, clients.Workflow)
	ctx = context.WithValue(ctx, EventSourceKey, clients.EventSource)
	ctx = context.WithValue(ctx, SensorKey, clients.Sensor)
	ctx = context.WithValue(ctx, KubeKey, clients.Kubernetes)
	ctx = context.WithValue(ctx, ClaimsKey, claims)
	return ctx, nil
}
```

So we can't just replace the context with the `cmd.Context()`, we would need to merge it. As the [`context.Merge` proposal is still open](https://github.com/golang/go/issues/36503), we would need to use something like https://github.com/teivah/onecontext.

Or, figure some other way 🙂

**Comment by Trojan295** [comment]
I created a PR in Argo, which would fix this problem:
https://github.com/argoproj/argo-workflows/pull/6667
