### ISSUE TITLE
Add pipeline to run integration test on k3d

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#492]
## Description

Recently, we added support for k3d (https://github.com/capactio/capact/issues/466). To ensure no regression, we need to create a pipeline that will run on each PR and main branch. It will be exactly the same as we have with the kind.

https://github.com/capactio/capact/blob/fa6712d8d3fc5767e063a763dc7717eb9ca22b3c/.github/workflows/pr-build.yaml#L390-L443

We need to add it as a parallel step to the `kind` one.

## AC

- Integration test are executed on k3d cluster, if failed, pipeline should be red
- Integration test on kind and k3d are run in parallel

- **Stretch:** 
    Use preloaded images for our dependencies. We should build image tarball only if something was changed in `deploy/kubernetes/charts`. Later, this tarball can be used by k3d. 
    ```
    # Cache images
    capact alpha archive-images helm -v --version @latest --helm-repo @latest --output ./archive.tar --save-component=neo4j,ingress-nginx,argo,cert-manager,kubed
    
    # Preload images
    DISABLE_MONITORING_INSTALLATION=true K3D_IMAGES_ARCHIVE=archive.tar CLUSTER_TYPE=k3d make test-integration
    ```
    
    Not sure where this tarball should be stored, as we may run to GitHub cache limits: https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy. Maybe it will be better to push it to our GCS.

## Reason

Ensure no regression. Additionally, test which environment is more stable and faster.

**Comment by thisisommore** [comment]
Can I give it a try?

**Comment by mszostok** [comment]
Hi @thisisommore! 

Feel free to take it :)

In the first phase, just focus on executing the integration test on `k3d`:
```bash
DISABLE_MONITORING_INSTALLATION=true K3D_IMAGES_ARCHIVE=archive.tar CLUSTER_TYPE=k3d make test-integration
```

If you need help, please join `#capact` channel on CNCF workspace: https://capact.io/community/slack 👍 

The problematic part is that the change needs to be tested on your fork. On our repo we use the `pull_request_target`  event which takes the workflow definition from the `main` branch. As a result, changes to any `capact/.github/workflows/*.yaml` files on pull-request are ignored on our pipelines.

**Comment by thisisommore** [comment]
I usually code in different branch even on fork, I guess in this case I have to code in main branch

**Comment by thisisommore** [comment]
Hey @mszostok I was working on it and got an error 
![image](https://user-images.githubusercontent.com/51229945/141242600-085f2e84-acca-4e12-addd-d2956e50f95a.png)
Can you please check if there is something wrong with my changes https://github.com/thisisommore/capact

**Comment by mszostok** [comment]
Hi @thisisommore, sorry for late response but I was on vacation during the long weekend ;)

Regarding your issues I found:
1. Unfortunately, you deleted the function call: https://github.com/thisisommore/capact/commit/c1649082f7201c00c1e383d5fa3d75faaf7681a2#diff-079edea40bca6863258884390b26184956a3f24fecaa122eb2c5803b1e14847cL99-L100. This is the reason that you don't see anything in the logs.
2. You commented out the code responsible for pushing images. In general that's ok but in normal workflow we use them later in integration test step to make it faster and reuse already built images. For your tests, you can simply change the ** BUILD_IMAGES** env to `true` on the integration step.
3. Don't define the ** K3D_IMAGES_ARCHIVE** as you don't produce this archive yet.


Here are the fixes that I added: https://github.com/mszostok/capact/commit/1e1eb598eb3a4411f6bb26a26a2ef79b05777697

Unfortunately, I got:
```
Node 'k3d-k3d-ci-capact-serverlb' is restarting for more than a minute now. Possibly it will recover soon (e.g. when it's waiting to join). Consider using a creation timeout to avoid waiting forever in a Restart Loop. [started 22:04 UTC]
```
I will try to debug that tomorrow :)

**Comment by mszostok** [comment]
Hi @thisisommore I figured out the problem, here is the PR with fix: https://github.com/capactio/capact/pull/566

after merging the above PR you can retry your pipelines with the changes that I mentioned here: https://github.com/capactio/capact/issues/492#issuecomment-969388850

I check that and it worked on my fork :)

**Comment by thisisommore** [comment]
Hi @mszostok sorry for late response, I have tried to merge your changes and new error(s) are shown 
![image](https://user-images.githubusercontent.com/51229945/143580974-0568c511-0c8b-4ebb-b45c-e84ff6790753.png)
