### ISSUE TITLE
Rewrite Local Hub to Go

### ISSUE THREAD

**Issue by pkosiec** [capactio/capact#605]
## Description

- Consider https://github.com/dosco/graphjin
- Implement 1:1 features that we already support in Local Hub already
vMake Local Hub to use PostgreSQL (Install Bitnami PostgreSQL Helm chart)
- Remember that in future we will extend it with multiple backends
- Do not support upgrade and migration from 0.5.0
- Extend TypeInstance GraphQL API with the `TypeInstance.spec.backend` field

## Related issues

See epic #604 for reason and use cases.

**Comment by mszostok** [comment]
Investigations showed that rewriting doesn't make sense at the current stage, for more info check #626
