### ISSUE TITLE
Handle multiple backends for the TypeInstance upload from workflow

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#634]
## Description
**Blocked by: https://github.com/capactio/capact/pull/630**

Modify TypeInstance create/update actions (named as "Argo actions") to take new input `context` as described in 3rd,4th and 5th step: [Workflow syntax - Create](https://github.com/capactio/capact/blob/main/docs/proposal/20211207-delegated-storage.md#workflow-syntax---create)

For backward compatibility:
  - Modify Helm and Terraform runners output and additional output under nested `value` property in Argo artifact
  - Make sure all manifests are up-to-date (at least compatible with new Argo artifact syntax)
  
  
**Acceptance Criteria**

- "Argo actions" reads mounted artifacts and render a proper GraphQL `createTypeInstances` mutation. Setting relations with a given backend should be skipped as it's done on Local Hub side.
- Handle `context` propagation in the Local Hub. Send in to a given backend if available.
- Create dedicated Capact manifests or [update existing ones](https://github.com/capactio/hub-manifests/tree/main/manifests/implementation/capactio/capact/validation) to showcase usage of the `backend.context` in Implementation manifest.
- Update integration test to test the `backend.context` propagation. We can use the `dotenv` provider, see: https://github.com/capactio/capact/issues/647

## Related issues

See epic #604 for reason and use cases.

**Comment by mszostok** [comment]
TODO: extract setting backend ID to dedicated storage with 2MD

**Comment by mkuziemko** [comment]
PRs created:
- https://github.com/capactio/capact/pull/657
- https://github.com/capactio/hub-manifests/pull/60

I included more information in the PRs itself.

**Comment by mkuziemko** [comment]
PR closed. I create one follow-up to this task [here](https://github.com/capactio/capact/issues/687).
